// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentHouseMembershipCart.Identity.DbContext;

#nullable disable

namespace StudentHouseMembershipCart.Identity.Migrations
{
    [DbContext(typeof(StudentHouseMembershipCartDatabaseContext))]
    [Migration("20231122165500_InitMoreData")]
    partial class InitMoreData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ROLE1",
                            ConcurrencyStamp = "032e22dd-1e7e-4791-b141-caa57f22aba7",
                            Name = "Student",
                            NormalizedName = "Student"
                        },
                        new
                        {
                            Id = "ROLE2",
                            ConcurrencyStamp = "9990f82d-a3d5-4812-9932-773a6a30672b",
                            Name = "Staff",
                            NormalizedName = "Staff"
                        },
                        new
                        {
                            Id = "ROLE3",
                            ConcurrencyStamp = "f402fd26-331e-40c7-a2a3-609996dc60a9",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ACCOUNT1",
                            RoleId = "ROLE1"
                        },
                        new
                        {
                            UserId = "ACCOUNT2",
                            RoleId = "ROLE2"
                        },
                        new
                        {
                            UserId = "ACCOUNT3",
                            RoleId = "ROLE3"
                        },
                        new
                        {
                            UserId = "ACCOUNT9",
                            RoleId = "ROLE1"
                        },
                        new
                        {
                            UserId = "ACCOUNT10",
                            RoleId = "ROLE1"
                        },
                        new
                        {
                            UserId = "ACCOUNT11",
                            RoleId = "ROLE1"
                        },
                        new
                        {
                            UserId = "ACCOUNT7",
                            RoleId = "ROLE2"
                        },
                        new
                        {
                            UserId = "ACCOUNT6",
                            RoleId = "ROLE2"
                        },
                        new
                        {
                            UserId = "ACCOUNT5",
                            RoleId = "ROLE2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Admin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90ca347f-831f-4b75-98bb-ae825b3efc15"),
                            AdminName = "Admin",
                            ApplicationUserId = "ACCOUNT4",
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 644, DateTimeKind.Local).AddTicks(674),
                            IsDelete = false
                        });
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Apartment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("StudentId");

                    b.ToTable("Apartment");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.AttendReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AttendenceStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("BookingDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingDetailOfPakcageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingDetailOfServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDoPackage")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReportWorkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailOfPakcageId");

                    b.HasIndex("BookingDetailOfServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("AttendReport");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentNewId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusContract")
                        .HasColumnType("int");

                    b.Property<double>("TotalPay")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ApartmentId");

                    b.HasIndex("PaymentNewId");

                    b.ToTable("Booking");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfPakcage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BookingDetailStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRe_Newed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOfPackageOrdered")
                        .HasColumnType("int");

                    b.Property<int>("RemainingTaskDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RenewStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPriceOfQuantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PackageId");

                    b.ToTable("BookingDetailOfPakcage");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BookingDetailStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRe_Newed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOfPackageOrdered")
                        .HasColumnType("int");

                    b.Property<int>("RemainingTaskDuration")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RenewStartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPriceOfQuantity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PackageId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BookingDetailOfService");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.BookingDetailStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingDetailOfPakcageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BookingDetailOfServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BookingDetailOfPakcageId");

                    b.HasIndex("BookingDetailOfServiceId");

                    b.HasIndex("StaffId");

                    b.ToTable("BookingDetailStaff");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8abb3dda-208b-4397-93c0-3a5269a90e3d"),
                            CategoryName = "Rửa xe",
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(4669),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("9df988f5-0382-4939-8eee-09d47b182bbb"),
                            CategoryName = "Nấu ăn cho em",
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(4773),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("375a894d-e8e5-4a84-a0b8-09f907992b46"),
                            CategoryName = "Shipping",
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(4776),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("8940e7f6-fd91-4402-a515-b9d55448c522"),
                            CategoryName = "hỗ trợ tài chính",
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(4779),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("21291667-7546-4825-9bad-840d648900a3"),
                            CategoryName = "dọn vệ sinh nhà cửa",
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(4781),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("ba0f3f23-9425-44ad-9d73-a7608381fd5f"),
                            CategoryName = "Bảo trì và sửa chữa",
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(4783),
                            IsDelete = false
                        },
                        new
                        {
                            Id = new Guid("a3ccb973-d6c4-4ef4-ae4b-36a97429a0b0"),
                            CategoryName = "Giặt đồ",
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(4785),
                            IsDelete = false
                        });
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.FeedBack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AttendReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeedBackDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedBackImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedBackName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FeedBackRating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FeedBackStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttendReportId")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("FeedBack");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DayDoServiceInWeek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfPerWeekDoPackage")
                        .HasColumnType("int");

                    b.Property<string>("PackageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalOriginalPrice")
                        .HasColumnType("float");

                    b.Property<double?>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("WeekNumberBooking")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.PackageService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("QuantityOfService")
                        .HasColumnType("int");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("ServiceId");

                    b.ToTable("PackageService");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.PaymentNew", b =>
                {
                    b.Property<string>("PaymentNewId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentDestinationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentRefId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RequiredAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentNewId");

                    b.ToTable("PaymentNew");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentNewId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PaymentTransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TranAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TranDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranRefId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TranStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentNewId");

                    b.ToTable("PaymentTransaction");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.ReportWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternativeReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("AttendReportId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionProcess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReportByStaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StaffSubstitableId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("WorkingDayExpect")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("WorkingDayReport")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkingStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttendReportId");

                    b.HasIndex("StaffId");

                    b.ToTable("ReportWork");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("OriginalPrice")
                        .HasColumnType("float");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ServiceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServiceType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("staffName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d36a73ed-78ae-46af-befd-7b90cbcfc479"),
                            Address = "Dong Nai",
                            ApplicationUserId = "ACCOUNT5",
                            Birthday = new DateTime(1999, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(4947),
                            IsDelete = false,
                            staffName = "Staff 1"
                        },
                        new
                        {
                            Id = new Guid("c085539d-76bd-4fe8-9444-12c21de6610b"),
                            Address = "An Giang",
                            ApplicationUserId = "ACCOUNT6",
                            Birthday = new DateTime(1990, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(5025),
                            IsDelete = false,
                            staffName = "Staff 2"
                        },
                        new
                        {
                            Id = new Guid("a8ded7dd-683f-4231-8c47-560375560eea"),
                            Address = "Long An",
                            ApplicationUserId = "ACCOUNT7",
                            Birthday = new DateTime(2000, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(5036),
                            IsDelete = false,
                            staffName = "Staff 3"
                        });
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.StaffCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffCategory");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9589c1a-3cbc-4215-bb84-b8fa7d719420"),
                            Address = "Đà Nẵng",
                            ApplicationUserId = "ACCOUNT9",
                            Birthday = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(5170),
                            IsDelete = false,
                            Phone = "0961868641"
                        },
                        new
                        {
                            Id = new Guid("b9cf3487-3d04-4cbf-85b7-e33360566485"),
                            Address = "Hồ Chí Minh",
                            ApplicationUserId = "ACCOUNT10",
                            Birthday = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(5184),
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(5183),
                            IsDelete = false,
                            Phone = "0312357823"
                        },
                        new
                        {
                            Id = new Guid("46f50a4a-327e-47f1-a43c-d31b6b39b939"),
                            Address = "Hà Nội",
                            ApplicationUserId = "ACCOUNT11",
                            Birthday = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(5187),
                            Created = new DateTime(2023, 11, 22, 23, 54, 59, 728, DateTimeKind.Local).AddTicks(5186),
                            IsDelete = false,
                            Phone = "0987451632"
                        });
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ACCOUNT1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "44b32d48-a11a-4e95-b77b-90e090a486c2",
                            Email = "vi@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Nguyen Vi",
                            LockoutEnabled = false,
                            NormalizedEmail = "VI@GMAIL.COM",
                            NormalizedUserName = "VI@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEOT7iBkclLxUkD4QiOQD1dbbKsLAz91zEic1OzxBNTZ3ZuwtGC9t1jjTiR7y7/vq4A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "30476ffd-45d7-4f1d-b93d-08678623ce49",
                            TwoFactorEnabled = false,
                            UserName = "vi@gmail.com"
                        },
                        new
                        {
                            Id = "ACCOUNT2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dc6c2372-0b87-44c5-9255-47b33a1b5770",
                            Email = "nhan@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Nguyen Nhan",
                            LockoutEnabled = false,
                            NormalizedEmail = "NHAN@GMAIL.COM",
                            NormalizedUserName = "NHAN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEG5a1Ep/sM5UoHeupRhiNvTrnLQ1a71agE9oGBYE1Hk1lWVzMtzfKD9nQ78olKHkFA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "90d59afb-8e92-4243-a447-f8de6c41bc76",
                            TwoFactorEnabled = false,
                            UserName = "nhan@gmail.com"
                        },
                        new
                        {
                            Id = "ACCOUNT3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5412a8ff-21e2-4a07-a5c9-0953073d108d",
                            Email = "dai@gmail.com",
                            EmailConfirmed = true,
                            FullName = "Nguyen Dai",
                            LockoutEnabled = false,
                            NormalizedEmail = "DAI@GMAIL.COM",
                            NormalizedUserName = "DAI@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAED9T+bPYt3y6WZ5TL+PiwdxMVlmNmAw4kUiic9vNYg49e8TZLWqxMZDxq9x1rvoEfw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "db1d6de1-8272-425c-871a-4787e877852a",
                            TwoFactorEnabled = false,
                            UserName = "dai@gmail.com"
                        },
                        new
                        {
                            Id = "ACCOUNT4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fce7035d-38f9-4170-8d00-1bdac076137e",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            FullName = "admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAENRXrcI03PmJEIAHDQm7N0NFyHIRi61lMEZOp7I3nxpDBlvuE/2mZzvdvhb3Ovmeag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "231d072b-8448-4425-9a86-d57233367d6e",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "ACCOUNT5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "781836e0-9614-4919-9463-e8fb95621a51",
                            Email = "staff1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "staff",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF1@GMAIL.COM",
                            NormalizedUserName = "STAFF",
                            PasswordHash = "AQAAAAEAACcQAAAAEFkFawmxECPDZyHsbQDkfl5IyRhEcmcH4q+7vtJ79Sj4/7qIFtTDi9HYb7YBWhBdMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9fd59020-44ab-4c37-93e4-09cc1c74eaa0",
                            TwoFactorEnabled = false,
                            UserName = "staff"
                        },
                        new
                        {
                            Id = "ACCOUNT6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a0cbdec7-f95a-426d-a1dd-0d407068f241",
                            Email = "staff2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "staff2",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF2@GMAIL.COM",
                            NormalizedUserName = "STAFF2",
                            PasswordHash = "AQAAAAEAACcQAAAAELjF2Qo9ZpmtNr/z+n0pEgwv+Eni/DaD2bxctXN1TF773PapnrG72CY0/8auTpAHKQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "812de10f-4fa8-46cb-8fe4-5bf06cb6b18a",
                            TwoFactorEnabled = false,
                            UserName = "staff2"
                        },
                        new
                        {
                            Id = "ACCOUNT7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "550e9fe2-43ee-4e5e-b1b6-89344306c923",
                            Email = "staff3@gmail.com",
                            EmailConfirmed = true,
                            FullName = "staff3",
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF3@GMAIL.COM",
                            NormalizedUserName = "STAFF3",
                            PasswordHash = "AQAAAAEAACcQAAAAEFdZ3o0ZA6AoOHQZkS8uy3uqHMz0uxiVVvjYaegAd+WJNxMgP0D8oW+4Qr9vVaxbuw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "76ea003e-1822-451b-93f2-3d99c7762f7b",
                            TwoFactorEnabled = false,
                            UserName = "staff3"
                        },
                        new
                        {
                            Id = "ACCOUNT9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b4724f0-72fb-4e25-9db2-a2f30996db03",
                            Email = "student1@gmail.com",
                            EmailConfirmed = true,
                            FullName = "student1",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT1@GMAIL.COM",
                            NormalizedUserName = "STUDENT1",
                            PasswordHash = "AQAAAAEAACcQAAAAEFKTcERnS+vNVee4VLexb7Hj6C69xBBM+OrjfWQRrkBGHaAC1//GW4dv857f/czOfA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2c451dae-956c-4a80-8b18-a68c6939fbf6",
                            TwoFactorEnabled = false,
                            UserName = "student1"
                        },
                        new
                        {
                            Id = "ACCOUNT10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0df6c77d-ce82-45c1-98f7-fe499bf02d8e",
                            Email = "student2@gmail.com",
                            EmailConfirmed = true,
                            FullName = "student2",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT2@GMAIL.COM",
                            NormalizedUserName = "STUDENT2",
                            PasswordHash = "AQAAAAEAACcQAAAAEG++CZYQ+T2q6FAbNJxNVN6TAcK7JEGGnaMrtHHsTjYuZBQP+wnmybwsJGBc6COXMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1d822b3f-d2f4-48af-b111-285b86c41a75",
                            TwoFactorEnabled = false,
                            UserName = "student2"
                        },
                        new
                        {
                            Id = "ACCOUNT11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5f235f56-5225-4233-97f1-ac37b2b5f2f7",
                            Email = "student3@gmail.com",
                            EmailConfirmed = true,
                            FullName = "student3",
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT3@GMAIL.COM",
                            NormalizedUserName = "STUDENT3",
                            PasswordHash = "AQAAAAEAACcQAAAAEMyLUiTVbzG+PDRWbwkSje1kTUsOzuoap6amx2glixY5e2ArByugZmhrKXsUI0fdUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e844e583-83be-4292-a766-0af7d3f0750d",
                            TwoFactorEnabled = false,
                            UserName = "student3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Admin", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", "ApplicationUser")
                        .WithOne("Admin")
                        .HasForeignKey("StudentHouseMembershipCart.Domain.Entities.Admin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Apartment", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Region", "Region")
                        .WithMany("Apartment")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Student", "Student")
                        .WithMany("Apartment")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.AttendReport", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfPakcage", null)
                        .WithMany("AttendReport")
                        .HasForeignKey("BookingDetailOfPakcageId");

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfService", null)
                        .WithMany("AttendReport")
                        .HasForeignKey("BookingDetailOfServiceId");

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Booking", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Apartment", "Apartment")
                        .WithMany("Booking")
                        .HasForeignKey("ApartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.PaymentNew", "PaymentNew")
                        .WithMany()
                        .HasForeignKey("PaymentNewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apartment");

                    b.Navigation("PaymentNew");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfPakcage", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingDetailOfPakcage")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Package", "Package")
                        .WithMany("BookingDetailOfPakcage")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfService", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Booking", "Booking")
                        .WithMany("BookingDetailOfService")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Package", null)
                        .WithMany("BookingDetailOfService")
                        .HasForeignKey("PackageId");

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.BookingDetailStaff", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfPakcage", null)
                        .WithMany("BookingDetailStaff")
                        .HasForeignKey("BookingDetailOfPakcageId");

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfService", null)
                        .WithMany("BookingDetailStaff")
                        .HasForeignKey("BookingDetailOfServiceId");

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Staff", "Staff")
                        .WithMany("BookingDetailStaff")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.FeedBack", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.AttendReport", "AttendReports")
                        .WithOne("FeedBack")
                        .HasForeignKey("StudentHouseMembershipCart.Domain.Entities.FeedBack", "AttendReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Student", "Students")
                        .WithMany("FeedBack")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendReports");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.PackageService", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Package", "Package")
                        .WithMany("PackageService")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Service", "Service")
                        .WithMany("PackageService")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.PaymentNew", "PaymentNew")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("PaymentNewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentNew");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.ReportWork", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.AttendReport", "AttendReport")
                        .WithMany()
                        .HasForeignKey("AttendReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Staff", "Staff")
                        .WithMany("ReportWork")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendReport");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Service", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Category", "Category")
                        .WithMany("Service")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Staff", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", "ApplicationUser")
                        .WithOne("Staff")
                        .HasForeignKey("StudentHouseMembershipCart.Domain.Entities.Staff", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.StaffCategory", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Category", "Category")
                        .WithMany("StaffCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StudentHouseMembershipCart.Domain.Entities.Staff", "Staff")
                        .WithMany("StaffCategories")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Student", b =>
                {
                    b.HasOne("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", "ApplicationUser")
                        .WithOne("Student")
                        .HasForeignKey("StudentHouseMembershipCart.Domain.Entities.Student", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Apartment", b =>
                {
                    b.Navigation("Booking");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.AttendReport", b =>
                {
                    b.Navigation("FeedBack")
                        .IsRequired();
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Booking", b =>
                {
                    b.Navigation("BookingDetailOfPakcage");

                    b.Navigation("BookingDetailOfService");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfPakcage", b =>
                {
                    b.Navigation("AttendReport");

                    b.Navigation("BookingDetailStaff");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.BookingDetailOfService", b =>
                {
                    b.Navigation("AttendReport");

                    b.Navigation("BookingDetailStaff");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Category", b =>
                {
                    b.Navigation("Service");

                    b.Navigation("StaffCategories");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Package", b =>
                {
                    b.Navigation("BookingDetailOfPakcage");

                    b.Navigation("BookingDetailOfService");

                    b.Navigation("PackageService");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.PaymentNew", b =>
                {
                    b.Navigation("PaymentTransactions");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Region", b =>
                {
                    b.Navigation("Apartment");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Service", b =>
                {
                    b.Navigation("PackageService");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Staff", b =>
                {
                    b.Navigation("BookingDetailStaff");

                    b.Navigation("ReportWork");

                    b.Navigation("StaffCategories");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.Entities.Student", b =>
                {
                    b.Navigation("Apartment");

                    b.Navigation("FeedBack");
                });

            modelBuilder.Entity("StudentHouseMembershipCart.Domain.IdentityModels.ApplicationUser", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Staff")
                        .IsRequired();

                    b.Navigation("Student")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
